import type { Metadata } from "next";
import "./globals.css";
import StyledComponentsRegistry from '../lib/registry'
import Header from "@/components/Header/Header";
import MainContent from "@/components/MainContent/MainContent";
import Footer from "@/components/Footer/Footer";
import { TrashProvider } from "@/contexts/TrashContext";
import TrashModal from "@/components/TrashModal/TrashModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        <TrashProvider>
          <StyledComponentsRegistry>
            <div className="app-container">
              <Header />
              <MainContent>{children}</MainContent>
              <Footer />
            </div>
            <TrashModal />
          </StyledComponentsRegistry>
        </TrashProvider>
      </body>
    </html>
  )
}
